-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('ADMINISTRADOR', 'GESTOR_CONTRATO', 'FISCAL_ADMINISTRATIVO', 'FISCAL_TECNICO', 'ORDENADOR_DESPESAS');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "UserRole" NOT NULL DEFAULT 'GESTOR_CONTRATO';
